/* Coordinates are WGS84 representative points, not promised entrances. */
window.TRIP = {
  places: [
    {id:'yuanmingyuan',n:'01',name:'圆明园',lat:40.00722,lng:116.29250,day:1,area:'海淀 · 西北',duration:'2–3 小时',fixed:'10/1 下午已定',note:'抵京后先入住或寄存行李。园区很大，选一片慢慢逛；想看大水法，优先规划西洋楼遗址片区。',entry:'圆明园遗址公园东门',source:'https://www.yuanmingyuanpark.cn/'},
    {id:'ditan',n:'02',name:'地坛公园',lat:39.95142,lng:116.40970,day:2,area:'北二环 · 安定门外',duration:'1–1.5 小时',note:'看古树、散步，不用走遍全园。想睡懒觉可挪到 10/4 傍晚；国庆不保证银杏已金黄。',entry:'地坛公园南门',source:'https://gygl.beijing.gov.cn/mlgy/mlgy_lsmy/201911/t20191129_734014.html'},
    {id:'tiantan',n:'03',name:'天坛',lat:39.88220,lng:116.40660,day:2,area:'东城 · 城南',duration:'约 3 小时',fixed:'10/2 下午已定',note:'建议 14:00 左右入园，选含核心景点的票种。东门 → 祈年殿 → 丹陛桥 → 皇穹宇、回音壁 → 圜丘 → 南门。',entry:'天坛公园东门',source:'https://www.tiantanpark.cn/index.html'},
    {id:'tsinghua',n:'04',name:'清华大学',lat:40.00000,lng:116.32667,day:3,area:'海淀 · 西北',duration:'约 3 小时',fixed:'10/3 上午已定',note:'按入校安排和现场开放范围游览。二校门、清华学堂、大礼堂、水木清华、近春园挑重点；下午留白休息。',entry:'清华大学',source:'https://www.tsinghua.edu.cn/zjqh/syxx/xycg.htm'},
    {id:'yonghe',n:'05',name:'雍和宫',lat:39.94709,lng:116.41092,day:4,area:'东城 · 雍和宫片区',duration:'约 2 小时',note:'上午先参观寺院，再吃午饭。预留排队时间，沿中轴参观；请查看官方当日开放和购票安排。',entry:'雍和宫游客入口',source:'https://s.visitbeijing.com.cn/attraction/117887'},
    {id:'guozijian',n:'06',name:'国子监',lat:39.94556,lng:116.40694,day:4,area:'东城 · 国子监街',duration:'约 2 小时',note:'这里按进入孔庙和国子监博物馆安排，不只是逛国子监街。看辟雍、古树与古代教育文化。',entry:'孔庙和国子监博物馆',source:'https://s.visitbeijing.com.cn/attraction/117801'},
    {id:'wudaoying',n:'07',name:'五道营胡同',lat:39.94785,lng:116.40505,day:4,area:'东城 · 安定门内',duration:'1–2 小时',note:'逛小店、喝咖啡，找个地方坐下来。若接着去地坛，把胡同游览缩短到 1 小时。',entry:'五道营胡同'},
    {id:'nanluo',n:'08',name:'南锣鼓巷',lat:39.93730,lng:116.39650,day:5,area:'东城 · 胡同街区',duration:'约 1.5 小时',note:'从南口向北走，适当逛开放的支巷。主街拥挤时不用坚持走遍，也不要进入私人院落。',entry:'南锣鼓巷南口'},
    {id:'gulou',n:'09',name:'鼓楼',lat:39.94019,lng:116.38964,day:5,area:'老城 · 中轴线',duration:'0.5–1.5 小时',note:'从南锣北口沿鼓楼东大街向西。可登楼参观，也可只看外观；之后经烟袋斜街前往什刹海。',entry:'北京鼓楼'},
    {id:'shichahai',n:'10',name:'什刹海',lat:39.93780,lng:116.38510,day:5,area:'西城 · 前海、后海',duration:'2 小时起',note:'地图标在银锭桥附近的湖区代表位置。沿前海、后海选择一段散步，等傍晚灯亮，不必环湖走完。',entry:'什刹海银锭桥'},
    {id:'beihai',n:'11',name:'北海公园',lat:39.92444,lng:116.38306,day:6,area:'西城 · 皇城西北',duration:'约 2.5 小时',note:'北门进，沿东岸向南游览，按体力选择琼华岛和白塔周边，再从东门出，步行衔接景山西门。',entry:'北海公园北门',source:'https://yllhj.beijing.gov.cn/ztxx/kpjd/202312/t20231222_3508028.shtml'},
    {id:'jingshan',n:'12',name:'景山公园',lat:39.92361,lng:116.39056,day:6,area:'西城 · 故宫北侧',duration:'1–1.5 小时',note:'从西门进，登万春亭俯瞰故宫与中轴线。登顶有台阶；返程日按交通时间提前结束。',entry:'景山公园西门',source:'https://yllhj.beijing.gov.cn/ztxx/kpjd/202312/t20231222_3508033.shtml'}
  ],
  days: [
    {id:1,date:'10.01',week:'周四',short:'初到北京',title:'抵京后，先逛一座园',color:'#a65c24',area:'海淀',pace:'半天 · 轻松',summary:'中午抵京，下午圆明园。把第一晚留给休息。',transport:'先寄存行李再游园。抵达时间较晚就缩短游览，不追求走遍圆明三园。',tips:'西洋楼遗址在园区东北侧。从南门到大水法有一段路，按想看的区域选择入口。',items:[{time:'中午',title:'抵京 · 午饭 · 入住',text:'先安顿行李；抵达和市内交通时间按实际情况预留。',rest:true},{time:'15:00–17:30',place:'yuanmingyuan'},{time:'晚上',title:'就近晚饭，早点休息',text:'不再跨城加景点。',rest:true}]},
    {id:2,date:'10.02',week:'周五',short:'古树与天坛',title:'在古树与殿宇间漫步',color:'#aa3844',area:'地坛 → 天坛',pace:'上午可选 · 下午已定',summary:'地坛是机动安排，天坛下午保留约 3 小时。',transport:'地坛南门附近接雍和宫站，乘地铁 5 号线前往天坛东门站。门到门约留 50–70 分钟，午饭另留。',tips:'天坛核心景点常规旺季 17:30 停止进入、18:00 关闭。公园晚间开放不代表祈年殿等仍可进入。',items:[{time:'09:30–11:00',place:'ditan',optional:true},{time:'11:00–14:00',title:'午饭 · 休息 · 前往天坛',text:'跨区交通留余量，午饭不要匆忙。',rest:true},{time:'14:00–17:00',place:'tiantan'},{time:'晚上',title:'吃饭后休息',text:'今天不追加夜游。',rest:true}]},
    {id:3,date:'10.03',week:'周六',short:'清华与留白',title:'半日清华，半日自由',color:'#327c78',area:'海淀',pace:'半天 · 充分留白',summary:'上午按已定安排进校，下午不赶下一站。',transport:'校门按预约或入校资格确定。校园较大，出行前先确认入口，别只导航到学校中心。',tips:'社会公众参观需实名预约；已有正常入校资格则按相应规则。这里的“已定”指用户已有计划，不代表代为完成预约。',items:[{time:'上午 · 按入校时段',place:'tsinghua'},{time:'12:00–13:30',title:'午饭，慢慢吃',text:'可在校园周边安排，不默认能使用校内食堂。',rest:true},{time:'下午至晚上',title:'把半天留给自己',text:'回住处休息，或在海淀就近喝咖啡。',rest:true}]},
    {id:4,date:'10.04',week:'周日',short:'寺院与胡同',title:'一片街区，慢慢逛一天',color:'#5267a8',area:'雍和宫 · 国子监',pace:'步行串联 · 有茶歇',summary:'先看寺院和博物馆，再坐进五道营的咖啡店。',transport:'雍和宫 → 国子监 → 五道营，各段步行约留 10–20 分钟；若去地坛，再留 20–30 分钟过街与步行。',tips:'国子监按入馆参观安排。地坛若移到今天，五道营缩短到 1 小时，傍晚再散步一小时即可。',items:[{time:'09:00–11:00',place:'yonghe'},{time:'11:00–12:30',title:'午饭与休息',text:'国子监街附近找一家合适的店，不追排队热点。',rest:true},{time:'12:30–14:30',place:'guozijian'},{time:'14:30–16:30',place:'wudaoying'}]},
    {id:5,date:'10.05',week:'周一',short:'鼓楼与湖边',title:'从胡同，走到湖边暮色',color:'#81548e',area:'南锣 · 鼓楼 · 什刹海',pace:'慢走 · 傍晚看湖',summary:'一路向西，逛累了就坐下，不要求环湖。',transport:'南锣南口向北 → 鼓楼东大街向西 → 鼓楼 → 烟袋斜街 → 银锭桥 → 什刹海。以步行为主。',tips:'国庆烟袋斜街、银锭桥附近可能拥挤。鼓楼可选登楼或只看外观，把时间留给湖边。',items:[{time:'10:00–11:30',place:'nanluo'},{time:'11:30–13:00',title:'午饭与休息',text:'在鼓楼东大街周边慢慢吃饭。',rest:true},{time:'13:00–14:30',place:'gulou'},{time:'14:30–16:00',title:'烟袋斜街 · 茶歇',text:'向西南走到银锭桥，途中休息一会儿。',rest:true},{time:'16:00 以后',place:'shichahai'}]},
    {id:6,date:'10.06',week:'周二',short:'北海与景山',title:'湖光与城景，为旅程收尾',color:'#367393',area:'皇城 · 北海 → 景山',pace:'半日至大半天',summary:'两座相邻公园，返程时间优先。',transport:'北海北门进、东门出 → 步行约 10–15 分钟 → 景山西门。景区代表点之间的虚线不是出入口路线。',tips:'本日假设傍晚或晚上离京。若中午离京，需提前挪动景点；取行李、去车站或机场另留时间。',items:[{time:'09:30–12:00',place:'beihai'},{time:'12:00–13:30',title:'午饭与休息',text:'景山前后街周边安排午饭。',rest:true},{time:'13:30–15:00',place:'jingshan'},{time:'之后',title:'取行李 · 返程或休息',text:'按实际车次或航班调整，不把时间卡满。',rest:true}]}
  ]
};
